version: '3'
services:
  ##########################################################################
  # Dependencies
  ##########################################################################

  # Consul
  consul:
    image: consul
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0

  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    # container_name: zipkin
    ports:
      - '9411:9411'

  # Unleash
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - '4242:4242'
    environment:
      DATABASE_HOST: 'unleash-db'
      DATABASE_NAME: 'unleash'
      DATABASE_USERNAME: 'unleash_user'
      DATABASE_PASSWORD: 'some_password'
      DATABASE_SSL: 'false'
    networks:
      - unleash
    depends_on:
      - unleash-db
  unleash-db:
    environment:
      POSTGRES_DB: 'unleash'
      POSTGRES_PASSWORD: 'some_password'
      POSTGRES_USER: 'unleash_user'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    expose:
      - '5433:5432'
    networks:
      - unleash
    image: postgres:10-alpine

networks:
  unleash:
    name: unleash
  
