version: '3'
services:
  ##########################################################################
  # Dependencies
  ##########################################################################

  # Consul
  consul:
    image: consul
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0

  # Zipkin
  zipkin:
    image: openzipkin/zipkin
    # container_name: zipkin
    ports:
      - 9411:9411

  # Unleash
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@unleash-db/postgres
    depends_on:
      - unleash-db
  unleash-db:
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - "5432"
    image: postgres:10-alpine
